### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by VernitaJ** [DIT112-V21/group-02#5]
2.2 As a user, I want to see the condition of my car through a ‘health bar’ on the screen.

Acceptance Criteria: When I drive into another vehicle, or an obstacle, my health points will decrease and the race will end if my health goes down to 0.

*Refers to FR 1.12

**Comment by worldisyoursdude** [comment]
Damage done should be, imo, calculated the same way as impact is calculated:

> I = impact
> F = Force 
> m = Mass of car
> a = acceleration

Assuming that 

> I = F

 and assuming that 

> m = 1300 KG 

which is the average weight of a compact car (this value will change depending on which car model we decide to use), we can use the following formula to calculate the impact of the car

> I = F = 1300 * a

Then, judging by the car's HP count (unknown yet, we can assume 10,000 HP points for the sake of example), we can set an appropriate percentage, because 91000 damage per hit at max speed (70, no?) just sounds slightly too much.  Maybe the percentage goes down as the number scales up? So, for example, anything under 1300 applies at 100%, while something like 7000 damage has only 30% applied?

**Comment by VernitaJ** [comment]
The health bar is implemented in the Monster Map PR.
